### ISSUE TITLE
Fast click

### ISSUE THREAD

**Issue by teoprog** [jspinak/brobot#10]
Is it possible to perform a fast click instead of a normal click? I have a button that cancels the option if the click is held for too long. Based on my tests, it seems that this is causing the problem.

**Comment by jspinak** [comment]
By default, the click is instantaneous, similar to a typical human click action. There are two action options that can affect this, `pauseAfterMouseDown` and `pauseBeforeMouseUp`, but these are set to 0 by default. You have more control of a click when combining MOVE, MOUSE_UP, and MOUSE_DOWN actions. You can play around with this, but I don't think you can get a faster click. This is also the same in SikuliX.

```
action.perform(MOVE, someImage);
action.perform(MOUSE_DOWN);
action.perform(MOUSE_UP);
```

**Comment by teoprog** [comment]
It seems weird because with Sikulix, the click action works perfectly, and in Brobot, the click is registered as a success and clicks at the exact same location. However, in Brobot, the click action on this case doesn't work. Through many manual tests, it seems I had the same behavior if I clicked long (like nothing happened), but if I clicked fast, it moved to the next state correctly.

I think the best would be for me to send you the website link by email so you can better understand my problem, if that is okay with you.

**Comment by jspinak** [comment]
Sure, you can send the link. One question - is it the first click your app makes?

**Comment by teoprog** [comment]
Ok, I sent you the email. It is the first click action, but not the first state (I performed an action beforehand that wasn't a click). However, I'm certain the click works because by changing the click image to another element on the page (for testing), the click action worked.

**Comment by jspinak** [comment]
This could be an issue with the focused window.

I'm assuming these are the steps you take when you run the app:
1. Run the app in your IDE
2. ALT-TAB to get to the automated application (or some other selection method)

This is a typical way to run a Brobot application, especially during development, but the selected window is often not the focused app. This helps:
3. Click manually somewhere inside the automated application to make sure it's the focused app, or have your app click some background image (where clicking does nothing) inside the automated application.

When the app to automate is not the focused window, clicking somewhere on it will make it the focused window but it won't actually click on it. Image recognition works regardless of the focused window. This is rarely an issue after the first click.

**Comment by teoprog** [comment]
I've tried adding the clicking action on this element multiple times, and it still didn't work. 
I also attempted to replace the image being clicked with another image of a different element, and that worked fine
so I can say it is not a focused app problem.

**Comment by jspinak** [comment]
Experiment with the click a bit. I would start by adding a small pause to make the click slower. You can also try slowing down the mouse movement or adding a pause before the click.

**Comment by teoprog** [comment]
I already tried something like this:
````java
    private boolean gotoAbout() {
        action.perform(MOVE, door1.getDoor1()).isSuccess();
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        action.perform(CLICK, door1.getDoor1()).isSuccess();
        return action.perform(CLICK, door1.getDoor1()).isSuccess();
    }
```


But it didn't work. I really think it is because the click action is not fast enough. I think more tests on the website I sent you by email would help you understand my problem better.

**Comment by teoprog** [comment]
I just tried with MOUSE_UP and MOUSE_DOWN; it didn't work as well.

**Comment by jspinak** [comment]
About your code above:

One of the main benefits of model-based GUI automation is the ability to do code-based testing of your automation application. Brobot uses the model of your GUI environment (the state structure you created) to simulate the GUI and actions taken. When you write GUI automation code outside of the framework, like `Thread.sleep(2000)`, you lose the ability to do code-based testing. Also, Brobot uses actions as objects to encourage thinking about GUI automation as a set of building blocks that can be rearranged dynamically during automation. Using pauses in the way you do above is more characteristic of process-based GUI automation (do A, then B, then C). https://jspinak.github.io/brobot/docs/introduction/core-features/processes-as-objects

`.isSuccess()` returns a boolean and is only necessary when you need to know if the action succeeded. `action.perform(...)` returns a `Matches` object.

You're going to have to experiment with the click yourself. You can start with the suggestions I made above. Performing CLICK twice is not the same as performing a double-click. The documentation should be your first point of reference. Pauses can be found here: https://jspinak.github.io/brobot/docs/API/data-types/actionOptions#pauses-and-delays. Click options are here: https://jspinak.github.io/brobot/docs/API/data-types/actionOptions#click-options.

**Comment by teoprog** [comment]
I've tried doing what you said like this:
```java
    private boolean gotoAbout() {
        ActionOptions actionOptions = new ActionOptions.Builder()
                .setAction(ActionOptions.Action.CLICK)
                .setClickType(ClickType.Type.DOUBLE_LEFT)
                .setMinSimilarity(0.45)
                .setPauseBeforeBegin(2.0)
                .build();


        return action.perform(actionOptions, door1.getDoor1()).isSuccess();
    }
```

However, it seems like I have this type of error:
```csharp
|CLICK door1.doorTest2| CLICK move mouse to L[1409,861]@S(0) Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
```
Since the message is very unclear, I was wondering if you have any idea why this happens.

**Comment by jspinak** [comment]
Can you post the stack trace? The error messages usually show the lines that were executed leading up to this error.

**Comment by teoprog** [comment]
I downloaded the latest version of Brobot today and tried using double click and pauses, but nothing changed (the click is logged as successful in the console, but nothing actually happens). I really think it is a Brobot bug because when I test it with Sikulix, it works normally. Honestly, for my application, this is a critical issue because the click is registered as working, but on many different elements, the clicks are not actually working. It would be great if you could fix it.

**Comment by jspinak** [comment]
It appears that `pauseAfterMouseDown` and `pauseBeforeMouseUp` were set to the Sikuli drag defaults of 0.3 in the ActionOptions Builder. If you refresh the project, the default values are now 0.

In the future, if you think there is something weird with an action, try debugging with a break point after the ActionOptions variable is created. This will show you all of the action options in your browser debug window.

Hope this change fixes your problem.
