### ISSUE TITLE
StateService issue

### ISSUE THREAD

**Issue by teoprog** [jspinak/brobot#6]
Like my previous issue, it seems that StateService (here https://jspinak.github.io/brobot/docs/tutorial-basics/states/) no longer exists. Could I have an explanation of the changes ?

**Comment by jspinak** [comment]
StateService is now AllStatesInProjectService. 

Since 1.0.7 will provide a database that can store different projects, I renamed the class AllStatesInProjectService to emphasize that it only accesses the states in the selected project.
