### ISSUE TITLE
FinishTransition issue

### ISSUE THREAD

**Issue by teoprog** [jspinak/brobot#9]
I tried to help me with the Mr. Doob app for doing my application however, I thought that I had understood that the finishTransition function's role was usually to determine if the transition was successful or not.

I was surprised when, no matter what I put in finalTransitions, I always got false if the image was not found on the page. I would like, in certains scenarios even if the image is not found on the screen, to still consider the test successful and proceed to the next step.
```java
package com.example.tw.model.homepage;

import io.github.jspinak.brobot.actions.actionExecution.Action;
import io.github.jspinak.brobot.actions.actionOptions.ActionOptions;
import io.github.jspinak.brobot.manageStates.StateTransition;
import io.github.jspinak.brobot.manageStates.StateTransitions;
import io.github.jspinak.brobot.services.StateTransitionsRepository;
import org.springframework.stereotype.Component;

import java.io.IOException;

import static io.github.jspinak.brobot.actions.actionOptions.ActionOptions.Action.FIND;
import static org.sikuli.script.Sikulix.print;

@Component
public class HomepageTransitions {

    private final Action action;
    private final Homepage homepage;
    private final String url;

    public HomepageTransitions(StateTransitionsRepository stateTransitionsRepository,
                               Action action, Homepage homepage) {
        this.action = action;
        this.homepage = homepage;
        this.url = "a_url";

        StateTransitions transitions = new StateTransitions.Builder("homepage")
                .addTransitionFinish(this::finishTransition)
                .addTransition(new StateTransition.Builder()
                        .addToActivate("cookies")
                        .setFunction(this::gotoCookies)
                        .build())
                .build();
        stateTransitionsRepository.add(transitions);
    }

    private boolean finishTransition() {
        boolean isImageFound = action.perform(FIND, homepage.getChooseEngine()).isSuccess();
        print("Image found: " + isImageFound);
        if (!isImageFound) {
            navigateToUrl(url);
        }
        return true;
    }

    private boolean gotoCookies() {
        try {
            navigateToUrl(url);

        } catch (InterruptedException e) {
            return false;
        }
        return true;
    }
}
```
```java
package com.example.tw.model.homepage;

import io.github.jspinak.brobot.database.services.AllStatesInProjectService;
import io.github.jspinak.brobot.datatypes.state.state.State;
import io.github.jspinak.brobot.datatypes.state.stateObject.stateImage.StateImage;
import lombok.Getter;
import org.springframework.stereotype.Component;
import io.github.jspinak.brobot.datatypes.primitives.location.Position;
@Component
@Getter
public class Homepage {

    private StateImage chooseEngine = new StateImage.Builder()
            .addPattern("chooseEngine")
            .build();

    private State state = new State.Builder("homepage")
            .withImages(chooseEngine)
            .build();

    public Homepage(AllStatesInProjectService stateService) {
        stateService.save(state);
    }
}

```

No matter the changes I make to FinishTransition, I always get the same return message:
```csharp
homepage.|FIND homepage.chooseEngine| Find.FIRST FIND  ✘
Open State about
Find path: [] -> about
✘Path to state not found.
✘ All paths tried, open failed.
Active States: []
```

**Comment by jspinak** [comment]
When the application first starts, it tries to find the active states. It does this by searching for images in the initial states, which you set in the SpringBootApplication class. Transitions only occur when you go from one state to another, but at the beginning of the application there are no active states.

There are ways to hard-code the start states. The easiest is with the `StateMemory` class, which holds the current active states. Use the method `addActiveState(String activeState)`. Instead of 
```
InitialStates initialStates = context.getBean(InitialStates.class);
initialStates.addStateSet(100, "homepage");
initialStates.findIntialStates();
```

use
```
StateMemory stateMemory = context.getBean(StateMemory.class);
stateMemory.addActiveState("homepage");
```

I wouldn't recommend doing this. Every state should have recognizable images and using StateMemory directly can make your application unstable and difficult to test. It's less of a problem at the start of automation, but still not the best solution.

**Comment by teoprog** [comment]
Sorry, but I'm not sure I understood. So with addStateSet, if a state image is not found on the screen, the application automatically finishes unless I use the second method, right ?. I don't plan to use this often, only in specific situations. Also, I'd like to know how to specify after a transition that my next image might not be present on the page, just like we specified at the start of the app.

**Comment by jspinak** [comment]
In general, at any point in the automation, your application can get lost. There are classes that deal with this, including the UNKNOWN state that exists in every Brobot application (you can set up transitions for this state in your app) and the StateFinder class, which searches for all states to rebuild the list of active states. If your application cannot find its way to one of the states in your model, it will end. 

One of the main benefits of model-based GUI automation is to abstract movement, pathfinding, and state management during automation. If you start doing this manually you lose these benefits. 

`finishTransition() { return true; }` will always activate the state following an outgoing transition. However, you don't really know if the state is there, so I wouldn't recommend doing this. What exactly are you trying to do?

**Comment by teoprog** [comment]
What I want to do is define specific behaviors for certain transitions. For example, with the cookies, I check for the cookie popup on the page. If it’s not present, that’s fine. However, if it is present, I want to click "accept cookies." This double-choice scenario will be rare in my application and used only in very specific cases.

**Comment by jspinak** [comment]
There are various ways to do this. The Brobot way is to create states and transitions for your application and let the framework take care of movement for you. 

Your state structure will have these states (rename them to fit your app):
start_state, accept_cookies, page_after_accepting_cookies.

and these transitions:
start_state -> accept_cookies
start_state -> page_after_accepting_cookies
accept_cookies -> page_after_accepting_cookies

The path score is a heuristic that tells Brobot which path to try first. 
https://jspinak.github.io/brobot/docs/introduction/core-features/state-management#paths
Each state has a default score of 1 and each transition a default score of 0. Scores are added, so A -> B adds the scores of the two states and the transition together. If they have the defaults, the score for this path will be 1 + 0 + 1 = 2. 

Brobot will find the following paths from the start_state to the page_after_accepting_cookies:
start_state -> page_after_accepting_cookies (default score = 2)
start_state -> accept_cookies -> page_after_accepting_cookies (default score = 3)

You want your app to try the longer path first. If the cookies page isn't there, it will try the other path.
If you give the (start_state -> page_after_accepting_cookies) transition a score of 2, the score for the shorter path will be 4 and for the longer path 3. Paths with lower scores are tried first. 

Update the project to be able to set the score in the StateTransition.Builder class.
